apiVersion: k3d.io/v1alpha3
kind: Simple
name: roam-cluster
servers: 1
agents: 1
kubeAPI:
  host: "0.0.0.0"
  hostIP: "0.0.0.0"
image: rancher/k3s:latest
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,metrics-server
        nodeFilters:
          - server:*
