# Restish API configuration for qwex controller
# Usage: restish qwex [command]
#
# Examples:
#   restish qwex machines create
#   restish qwex machines start <machine-id>
#   restish qwex machines stop <machine-id>
#   restish qwex machines delete <machine-id>

qwex:
  base: http://localhost:3000
  spec_files:
    - http://localhost:3000/openapi.json
  profiles:
    default:
      headers:
        Content-Type: application/json
