apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
  - https://github.com/kubernetes-sigs/kueue/releases/download/v0.14.0/manifests.yaml
