[project]
name = "controller"
version = "0.1.0"
description = "Controller application for managing services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.13",
    "fastapi==0.119.0",
    "uvicorn[standard]==0.38.0",
]
