base: template://_images/ubuntu-lts

vmType: "vz"
rosetta:
  enabled: true
  binfmt: true

cpus: 2
memory: "2GiB"
disk: "50GiB"

networks:
  - vzNAT: true

provision:
  - mode: system
    script: |
      #!/usr/bin/env bash
      set -xe

      sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

message: |
  VM is ready!
