base: template://_images/ubuntu-lts

vmType: "vz"
rosetta:
  enabled: true
  binfmt: true

cpus: 2
memory: "2GiB"
disk: "50GiB"

networks:
  - vzNAT: true

provision:
  - mode: system
    script: |
      #!/usr/bin/env bash
      set -xe

      sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

      # Create k3s auto-recovery service
      sudo tee /etc/systemd/system/k3s-recovery.service > /dev/null << 'EOF'
      [Unit]
      Description=K3s Auto Recovery
      After=multi-user.target

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c 'if systemctl list-unit-files | grep -q k3s.service; then systemctl is-active --quiet k3s.service || systemctl restart k3s.service; fi'
      RemainAfterExit=no

      [Install]
      WantedBy=multi-user.target
      EOF

      sudo tee /etc/systemd/system/k3s-recovery.timer > /dev/null << 'EOF'
      [Unit]
      Description=K3s Auto Recovery Timer
      Requires=k3s-recovery.service

      [Timer]
      OnBootSec=30sec
      OnUnitActiveSec=60sec

      [Install]
      WantedBy=timers.target
      EOF

      sudo mv /tmp/k3s-recovery.service /etc/systemd/system/
      sudo mv /tmp/k3s-recovery.timer /etc/systemd/system/
      sudo systemctl daemon-reload
      sudo systemctl enable k3s-recovery.timer
      sudo systemctl start k3s-recovery.timer

message: |
  VM {{.Name}} is running.
