vmType: "vz"
rosetta:
  enabled: true
  binfmt: true

cpus: 2
memory: "2GiB"
disk: "50GiB"

networks:
  - vzNAT: true

mountType: "virtiofs"
mounts:
  - location: "~"
    mountPoint: /home/user.linux
    writable: false

message: |
  VM is ready!

  Next steps:
    1. Setup Tailscale: just tailscale-control
    2. Install k3s: just k3s-control-up
    3. Get kubeconfig: just kubeconfig
