base: template://_images/ubuntu-lts

vmType: "vz"
rosetta:
  enabled: true
  binfmt: true

cpus: 2
memory: "4GiB"
disk: "30GiB"

networks:
  - vzNAT: true

provision:
  - mode: system
    script: |
      #!/usr/bin/env bash
      set -xe

      sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

message: |
  VM is ready!

  Next steps:
    1. Setup Tailscale: just tailscale-agent 
    2. Install k3s: just k3s-agent-up
